import React from 'react';
import { SymptomCategory } from '../types';
import { StomachIcon } from '../components/icons/StomachIcon';
import { LungsIcon } from '../components/icons/LungsIcon';
import { HeadIcon } from '../components/icons/HeadIcon';
import { ThermometerIcon } from '../components/icons/ThermometerIcon';
import { HeartbeatIcon } from '../components/icons/HeartbeatIcon';
import { ChestPainIcon } from '../components/icons/ChestPainIcon';
import { DizzyIcon } from '../components/icons/DizzyIcon';
import { SwollenFeetIcon } from '../components/icons/SwollenFeetIcon';
import { BlurryVisionIcon } from '../components/icons/BlurryVisionIcon';
import { BrainFogIcon } from '../components/icons/BrainFogIcon';
import { TremorIcon } from '../components/icons/TremorIcon';
import { UrinaryIcon } from '../components/icons/UrinaryIcon';
import { PelvicPainIcon } from '../components/icons/PelvicPainIcon';
import { LibidoIcon } from '../components/icons/LibidoIcon';
import { JointPainIcon } from '../components/icons/JointPainIcon';
import { MusclePainIcon } from '../components/icons/MusclePainIcon';
import { SkinIcon } from '../components/icons/SkinIcon';
import { WoundIcon } from '../components/icons/WoundIcon';
import { BrittleNailsIcon } from '../components/icons/BrittleNailsIcon';

// SYMPTOM CATEGORIES & SYMPTOMS
export const symptomCategories: SymptomCategory[] = [
  {
    id: 'cat_general',
    name: 'Général',
    symptoms: [
      { id: 's_fatigue', label: 'Fatigue intense', icon: <MusclePainIcon className="transform -scale-x-100" /> },
      { id: 's_fever', label: 'Fièvre', icon: <ThermometerIcon /> },
      { id: 's_chills', label: 'Frissons', icon: <ThermometerIcon /> },
      { id: 's_weight_loss', label: 'Perte de poids inexpliquée', icon: <SkinIcon /> },
      { id: 's_thirst', label: 'Soif excessive', icon: <StomachIcon /> },
    ],
  },
  {
    id: 'cat_head',
    name: 'Tête & Neurologique',
    symptoms: [
      { id: 's_headache', label: 'Maux de tête', icon: <HeadIcon /> },
      { id: 's_dizzy', label: 'Vertiges', icon: <DizzyIcon /> },
      { id: 's_blurry_vision', label: 'Vision floue', icon: <BlurryVisionIcon /> },
      { id: 's_brain_fog', label: 'Difficulté de concentration', icon: <BrainFogIcon /> },
      { id: 's_tremor', label: 'Tremblements', icon: <TremorIcon /> },
    ],
  },
  {
    id: 'cat_heart',
    name: 'Cœur & Circulation',
    symptoms: [
      { id: 's_palpitations', label: 'Palpitations', icon: <HeartbeatIcon /> },
      { id: 's_chest_pain', label: 'Douleur à la poitrine', icon: <ChestPainIcon /> },
      { id: 's_short_breath', label: 'Essoufflement', icon: <LungsIcon /> },
      { id: 's_swollen_feet', label: 'Pieds / Chevilles gonflés', icon: <SwollenFeetIcon /> },
    ],
  },
    {
    id: 'cat_respiratory',
    name: 'Respiratoire',
    symptoms: [
        { id: 's_cough', label: 'Toux persistante', icon: <LungsIcon /> },
        { id: 's_wheezing', label: 'Sifflements respiratoires', icon: <LungsIcon /> },
        { id: 's_stuffy_nose', label: 'Nez bouché', icon: <HeadIcon /> },
    ],
  },
  {
    id: 'cat_digestive',
    name: 'Digestif',
    symptoms: [
      { id: 's_heartburn', label: 'Brûlures d\'estomac', icon: <StomachIcon /> },
      { id: 's_nausea', label: 'Nausées / Vomissements', icon: <StomachIcon /> },
      { id: 's_bloating', label: 'Ballonnements', icon: <StomachIcon /> },
      { id: 's_abdominal_pain', label: 'Douleurs abdominales', icon: <StomachIcon /> },
    ],
  },
  {
    id: 'cat_urogenital',
    name: 'Uro-génital',
    symptoms: [
        { id: 's_urinary_difficulty', label: 'Difficulté à uriner', icon: <UrinaryIcon /> },
        { id: 's_frequent_urination', label: 'Urines fréquentes', icon: <UrinaryIcon /> },
        { id: 's_pelvic_pain', label: 'Douleurs pelviennes', icon: <PelvicPainIcon /> },
        { id: 's_libido', label: 'Baisse de libido', icon: <LibidoIcon /> },
    ],
  },
  {
    id: 'cat_joints',
    name: 'Os, Muscles & Articulations',
    symptoms: [
        { id: 's_joint_pain', label: 'Douleur articulaire', icon: <JointPainIcon /> },
        { id: 's_muscle_pain', label: 'Douleur musculaire', icon: <MusclePainIcon /> },
        { id: 's_stiffness', label: 'Raideur', icon: <JointPainIcon /> },
    ],
  },
  {
    id: 'cat_skin',
    name: 'Peau & Ongles',
    symptoms: [
        { id: 's_pale_skin', label: 'Pâleur', icon: <SkinIcon /> },
        { id: 's_jaundice', label: 'Jaunisse', icon: <SkinIcon /> },
        { id: 's_wound_healing', label: 'Plaies qui cicatrisent mal', icon: <WoundIcon /> },
        { id: 's_brittle_nails', label: 'Ongles cassants', icon: <BrittleNailsIcon /> },
    ],
  },
];

// Pathologies are now dynamically generated by the AI.
// The static data is no longer needed.